### ISSUE TITLE
[UX][Functional][Person] contact data manipulation tests

### ISSUE THREAD

**Issue by budi7** [ThunderID/HR_SYSTEM#40]
Edit data kontak person. tag item diubah dengan sembarang kata.

![1](https://cloud.githubusercontent.com/assets/10555410/8349177/f2008000-1b44-11e5-8c2e-f3dfdee3be2a.JPG)

![2](https://cloud.githubusercontent.com/assets/10555410/8349176/f1facf70-1b44-11e5-993d-b332b908a70d.JPG)

![3](https://cloud.githubusercontent.com/assets/10555410/8349178/f2986dde-1b44-11e5-8549-e94f944a6bb4.JPG)
- [x]  [question] apakah diperbolehkan untuk mengubah tag dari item, dimana data tersebut memiliki status [aktif]? 
- [x]  [question] apakah tag item yang di-entri memang tidak di filter, sehingga memungkinkan untuk memasukkan kata apapun dalam inputan item?
- [x]  [enhancement] saat sistem berhasil menyimpan data, membuat data, atau menghapus data, tidak ada pesan muncul untuk status bahwa data telah tersimpan.

**Comment by chelsymooy** [comment]
Q1 => Safety in observer
Q2 = > Diperbolehkan untuk custom message service
Q3 => #65
