### ISSUE TITLE
[Controller][mask][Person] contact

### ISSUE THREAD

**Issue by budi7** [ThunderID/HR_SYSTEM#41]
- [x]  input item tag bisa lebih dari 3 dengan bantuan spasi dan paste

![2](https://cloud.githubusercontent.com/assets/10555410/8349485/80229ae2-1b47-11e5-9dce-f5bebd0216f9.JPG)
- [ ] [Controller] untuk set aktif kalau tidak di centang tidak bisa menyimpan
  ![1](https://cloud.githubusercontent.com/assets/10555410/8349511/c7375486-1b47-11e5-9ecf-8bc4b7f54d8d.JPG)
  ![3](https://cloud.githubusercontent.com/assets/10555410/8349512/c73eb0d2-1b47-11e5-843d-2722d07d800f.JPG)

**Comment by chelsymooy** [comment]
Pertama : pengaman di controller
