### ISSUE TITLE
[Functional][Person] relation edit

### ISSUE THREAD

**Issue by budi7** [ThunderID/HR_SYSTEM#45]
buat data relasi baru dengan orang yang bekerja di organisasi yg sama (punya ID)
![4](https://cloud.githubusercontent.com/assets/10555410/8350736/470e1a3c-1b52-11e5-8a5e-b0a5f2ac943d.JPG)

pada kolom nama, sengaja dibuat berbeda. 
![3](https://cloud.githubusercontent.com/assets/10555410/8350768/795d39dc-1b52-11e5-9b5c-30de4d185874.JPG)
![1](https://cloud.githubusercontent.com/assets/10555410/8350747/65ec4bae-1b52-11e5-9bc8-134f579eddf0.JPG)
data relasi tersimpan
![2](https://cloud.githubusercontent.com/assets/10555410/8350814/ea663d2c-1b52-11e5-9099-7b2150180fd4.JPG)
- [x]  [Question] apakah tidak ada validasi bila mendaftarkan data relasi dari person yang punya ID?
- [x]  [Question] apakah data kontak memang tidak tersinkronisasi menggunakan input ID yang dimasukkan?
- [x]  [Question] kalau memang tidak otomatis tersinkron untuk data kontak, lalu bagaimana untuk menambahkan data kontak?

**Comment by chelsymooy** [comment]
Q1 => Observer handling
Q2 => Based on Q1
Q3 => Untuk data kontak bisa langsung di edit dari data karyawan (filter non karyawan / show)
