### ISSUE TITLE
[ERROR MESSAGE]template cuti

### ISSUE THREAD

**Issue by budi7** [ThunderID/HR_SYSTEM#48]
- [x]  [ERROR MESSAGE] nama & quota kosong
  ![1](https://cloud.githubusercontent.com/assets/10555410/8369493/ae6f5e06-1be4-11e5-88dc-7eed428fa56e.JPG)
- [x]  [ERROR MESSAGE] quota must be number
  ![1](https://cloud.githubusercontent.com/assets/10555410/8369515/41403a70-1be5-11e5-9898-83da7c202d75.JPG)
- [x]  typo page title (double "cuti")
  ![1](https://cloud.githubusercontent.com/assets/10555410/8369499/e099fc1a-1be4-11e5-8d8c-5726be8e6301.JPG)

**Comment by chelsymooy** [comment]
For Error message will be fixed in #63
