### ISSUE TITLE
[FUNCTIONAL]Tambah jatah cuti

### ISSUE THREAD

**Issue by budi7** [ThunderID/HR_SYSTEM#49]
- [x]  start & date dikosongkan, tetap bisa di save tanpa error.
- [x]  hak cuti tidak di centang => error

![1](https://cloud.githubusercontent.com/assets/10555410/8369630/c55cc43a-1be6-11e5-823f-c039516779b0.JPG)

**Comment by chelsymooy** [comment]
Persoalan di controller. add try catch
