### ISSUE TITLE
[Error Message][Functional] Template Dokumen

### ISSUE THREAD

**Issue by budi7** [ThunderID/HR_SYSTEM#50]
- [x]  hapus data item di template dokumen
  ![2](https://cloud.githubusercontent.com/assets/10555410/8370170/4bc364c8-1bee-11e5-873b-21576dae2c73.JPG)
  ![1](https://cloud.githubusercontent.com/assets/10555410/8370169/4b814782-1bee-11e5-8436-faec8f0040fd.JPG)
- [x] edit template dokumen.
  data dikosongkan dan di save
  ![2](https://cloud.githubusercontent.com/assets/10555410/8370244/29fcf6fa-1bef-11e5-831c-fdfacd446caa.JPG)
  ![1](https://cloud.githubusercontent.com/assets/10555410/8370246/2a4f0670-1bef-11e5-8fd4-9c20c183fe88.JPG)
- [x] error message name dan kategori
  ![1](https://cloud.githubusercontent.com/assets/10555410/8370257/79bea2ce-1bef-11e5-88bb-fb9dc1c3cb5e.JPG)
- [x] tambah data dokumen template, dimana data dikosongkan semua, tidak ada error message tapi keluar error beneran.
  ![1](https://cloud.githubusercontent.com/assets/10555410/8370305/38308ace-1bf0-11e5-9d00-507d6f19d60e.JPG)
  ![2](https://cloud.githubusercontent.com/assets/10555410/8370306/3832d19e-1bf0-11e5-9ea0-c5e08909da56.JPG)

**Comment by chelsymooy** [comment]
Disable template function
