### ISSUE TITLE
report attendance global

### ISSUE THREAD

**Issue by agilma** [ThunderID/HR_SYSTEM#91]
waktu report attendance per person diedit statusnya loss rate akan berubah, seperti gambar
![screenshot from 2015-07-06 16 42 57](https://cloud.githubusercontent.com/assets/4099329/8519613/2152c2de-23fe-11e5-864f-d688eb140107.png)

akan tetapi di report attedance global loss rate tetap sesuai data waktu sblm berubah
![screenshot from 2015-07-06 16 43 12](https://cloud.githubusercontent.com/assets/4099329/8519615/21ad37d2-23fe-11e5-8242-d3c27d2774ce.png)

**Comment by chelsymooy** [comment]
https://github.com/ThunderID/HR_SYSTEM/commit/54ac38d0062210f9ac2cc46b7c28eed3b36fe5ab#diff-cb4d57923a9c09d21ea600d66883bb6e
