### ISSUE TITLE
Laporan Kehadiran

### ISSUE THREAD

**Issue by budi7** [ThunderID/HR_SYSTEM#96]
1. hadir on time pulang on time, lost time ratio tidak wajar
   ![capture](https://cloud.githubusercontent.com/assets/10555410/8953898/f73d0d72-360b-11e5-811f-37b06ace499f.JPG)

2.overlap (100% ?)
![capture](https://cloud.githubusercontent.com/assets/10555410/8954061/5112ddda-360d-11e5-984a-cd2db73437e2.JPG)

**Comment by chelsymooy** [comment]
case 1. terhitung HC, alasan jamnya jam 00. tapi masuk jam 8.30 dan pulang 17.30 (tidak sesuai jadwal) jadi tlr = 100 % (updated)
