### ISSUE TITLE
[UI] Policy

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/HR_SYSTEM#97]
- type, value : 
- 'passwordreminder', string of time (pakai select bulan negatif -1 month sampai -12 months)
- 'assplimit', number (pakai numbernya html5, tidak boleh <=0)
- 'ulsplimit', number (pakai numbernya html5, tidak boleh <=0)
- 'hpsplimit', number (pakai numbernya html5, tidak boleh <=0)
- 'htsplimit', number (pakai numbernya html5, tidak boleh <=0)
- 'hcsplimit', number (pakai numbernya html5, tidak boleh <=0)
- 'firststatussettlement', string of time (pakai select bulan positif -1 day sampai -24 months)
- 'secondstatussettlement', string of time (pakai select bulan positif -1 day sampai -24 months) 
- 'firstidle', number (pakai numbernya html5, dalam menit)
- 'secondidle', number (pakai numbernya html5, dalam menit)
- 'thirdidle', number (pakai numbernya html5, dalam menit)
- 'extendsworkleave', string of time (pakai select bulan positif +1 month sampai +24 months)
- 'extendsmidworkleave', string of time (pakai select bulan positif +1 month sampai +24 months)
- 'firstacleditor', string of time (pakai select bulan positif -1 day sampai -24 months) 
- 'secondacleditor', string of time (pakai select bulan positif -1 day sampai -24 months)

**Comment by agilma** [comment]
https://github.com/ThunderID/HR_SYSTEM/commit/5192b44418aa810857d6c0c6597bd8d6fb8512a1
